Replacing `_dbt_max_partition` in incremental models that have a `partition_by` field
autotraderuk/dbt-dry-run pull request #15
Opened 2022-07-28 13:38 UTC by alvfermar-mp

# Description

See title

Fixes #10 

# Checklist:

- [x] I have run `make verify` and fixed any linting or test errors
- [x] I have added appropriate unit tests or if applicable an integration test
- [x] OPTIONAL: I have run `make integration` against a Big Query instance

2022-07-28 15:43 UTC, connor-charles requested changes
Looks pretty good! Just a few small changes then I think we can get this merged

2022-07-28 15:43 UTC, connor-charles commented on dbt_dry_run/test/node_runner/test_model_runner.py
> +    node.config.partition_by = PartitionBy(
SimpleNode takes a parameter for the config so you don't need to mutate it after it is created:

```python
    node = SimpleNode(
        unique_id="node1",
        ....
        table_config=NodeConfig(materialized="incremental", partition_by=PartitionBy(field="loader_ingestion_time", data_type="timestamp")),
    ).to_node()
```

2022-07-28 15:43 UTC, connor-charles commented on dbt_dry_run/test/node_runner/test_model_runner.py
> +def test_model_with_dbt_max_partition_variable_replaces_it() -> None:
The max partition variable isn't replaced more just prepended to the query so a better test name:

`test_partitioned_incremental_model_declares_dbt_max_partition_variable`

Or something like that?

2022-07-28 15:43 UTC, connor-charles commented on dbt_dry_run/test/node_runner/test_model_runner.py
> +DBT_MAX_PARTITION_DECLARATION = (
This isn't reused across the test suite so it can just be a local variable in `test_model_with_dbt_max_partition_variable_replaces_it`

2022-07-28 15:43 UTC, connor-charles commented on dbt_dry_run/node_runner/model_runner.py
> +        if node.config.materialized == "incremental" and node.config.partition_by:
To be more correct the materialisation only includes this variable if `"_dbt_max_partition" in node.compiled_sql` so another condition here in this if statement would mirror dbt's behaviour more closely

2022-07-29 06:56 UTC, alvfermar-mp commented
Thanks! I am have amended

2022-07-29 08:29 UTC, connor-charles requested changes
One last style change then we can merge, we can do a patch release after this has gone in.

2022-07-29 08:29 UTC, connor-charles commented on dbt_dry_run/test/node_runner/test_model_runner.py
> +    DBT_MAX_PARTITION_DECLARATION = (
For PEP8 this should be lower case `dbt_max_partition_declaration`

Then this is good to go 👍

2022-08-01 12:53 UTC, connor-charles commented on dbt_dry_run/test/node_runner/test_model_runner.py
> +    DBT_MAX_PARTITION_DECLARATION = (
Only for global constants at the module or class level. Google's style guide has a pretty good list: https://google.github.io/styleguide/pyguide.html#316-naming

But this looks good now! Thanks for changing. Will merge and do a release when I have time this week

2022-08-01 12:53 UTC, connor-charles approved these changes
Looks good. Thanks for the contribution @alvfermar-mp!

2022-08-01 12:55 UTC, merged